# Generated by Django 4.0 on 2021-12-18 00:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiarity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['user_profile', 'familiarity', 'skill_element'],
            },
        ),
        migrations.CreateModel(
            name='SkillElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_element_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['skill_set', 'skill_element_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_set_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['skills_set_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddConstraint(
            model_name='skillsset',
            constraint=models.UniqueConstraint(fields=('skills_set_name',), name='unique_skills_set'),
        ),
        migrations.AddField(
            model_name='skillelement',
            name='skill_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsUI.skillsset'),
        ),
        migrations.AddField(
            model_name='personalskills',
            name='skill_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsUI.skillelement'),
        ),
        migrations.AddField(
            model_name='personalskills',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsUI.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_profile'),
        ),
        migrations.AddConstraint(
            model_name='skillelement',
            constraint=models.UniqueConstraint(fields=('skill_element_name',), name='unique_skill_element'),
        ),
        migrations.AddConstraint(
            model_name='personalskills',
            constraint=models.UniqueConstraint(fields=('user_profile', 'skill_element'), name='unique_personal_skills'),
        ),
    ]
