# Generated by Django 4.0 on 2021-12-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalskills',
            options={'ordering': ['user_profile', '-familiarity', 'skill_element__skill_set', 'skill_element']},
        ),
    ]
