# Generated by Django 4.0 on 2021-12-19 00:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsUI', '0004_alter_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='skillelement',
            options={'ordering': ['skill_set', 'name']},
        ),
        migrations.AlterModelOptions(
            name='skillsset',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='skillelement',
            name='unique_skill_element',
        ),
        migrations.RemoveConstraint(
            model_name='skillsset',
            name='unique_skills_set',
        ),
        migrations.RenameField(
            model_name='skillelement',
            old_name='skill_element_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skillsset',
            old_name='skills_set_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 19)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddConstraint(
            model_name='skillelement',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_skill_element'),
        ),
        migrations.AddConstraint(
            model_name='skillsset',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_skills_set'),
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_seniority_name'),
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('rank',), name='unique_seniority_rank'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seniority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smsUI.seniority'),
        ),
    ]
