# Generated by Django 4.0 on 2021-12-19 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsUI', '0005_seniority_alter_skillelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 19, 0, 50, 9, 55847)),
        ),
    ]
